import React from 'react';

interface LegalDocProps {
  type: 'terms' | 'privacy';
  onBack: () => void;
}

const LegalDocs: React.FC<LegalDocProps> = ({ type, onBack }) => {
  return (
    <div className="flex flex-col h-full animate-[fadeIn_0.3s_ease-out]">
      <button 
        onClick={onBack}
        className="self-start text-white/70 hover:text-white transition-colors mb-4 group flex items-center gap-2 text-sm font-medium z-10 sticky top-0 bg-black/90 w-full py-2 backdrop-blur-md"
      >
        <i className="fa-solid fa-arrow-left group-hover:-translate-x-1 transition-transform"></i>
        Back to Login
      </button>

      <div className="overflow-y-auto pr-2 scrollbar-hide text-left">
        {type === 'terms' ? (
          <div className="space-y-4 text-gray-300 text-sm leading-relaxed">
            <h2 className="text-2xl font-bold text-white mb-4">Terms and Conditions</h2>
            <p className="text-xs text-gray-500 mb-4">Last Updated: February 2025</p>
            
            <h3 className="text-white font-bold">1. Introduction</h3>
            <p>Welcome to poorn. By accessing our website and using our AI video generation services, you agree to be bound by these Terms and Conditions.</p>

            <h3 className="text-white font-bold">2. Age Restriction</h3>
            <p>You must be at least 18 years of age to create an account or use our Services. By creating an account, you represent and warrant that you are at least 18 years old.</p>

            <h3 className="text-white font-bold">3. User Generated Content</h3>
            <p>You retain ownership of the content you generate. However, you grant poorn a non-exclusive license to host and display your content for the purpose of providing the service.</p>
            <p>You agree NOT to generate content that is illegal, non-consensual, promotes violence, or infringes on the rights of others. We reserve the right to ban users who violate these guidelines.</p>

            <h3 className="text-white font-bold">4. Subscriptions and Payments</h3>
            <p>Premium features require a subscription. Payments are processed securely via Stripe. You may cancel your subscription at any time; however, refunds are not provided for partial billing periods.</p>

            <h3 className="text-white font-bold">5. Limitation of Liability</h3>
            <p>poorn is provided "as is". We are not liable for any damages arising from your use of the service or the content generated by AI models.</p>
          </div>
        ) : (
          <div className="space-y-4 text-gray-300 text-sm leading-relaxed">
            <h2 className="text-2xl font-bold text-white mb-4">Privacy Policy</h2>
            <p className="text-xs text-gray-500 mb-4">Last Updated: February 2025</p>

            <h3 className="text-white font-bold">1. Information We Collect</h3>
            <p>We collect information you provide directly to us, such as your email address, username, and payment information (processed via Stripe). We also collect usage data related to how you interact with our AI tools.</p>

            <h3 className="text-white font-bold">2. How We Use Your Data</h3>
            <p>We use your data to: Provide and maintain the Service; Process transactions; Send you technical notices and support messages; Detect and prevent fraud.</p>

            <h3 className="text-white font-bold">3. Data Sharing</h3>
            <p>We do not sell your personal data. We may share data with third-party service providers (like Cloudinary for storage or Firebase for authentication) solely to provide the Service.</p>

            <h3 className="text-white font-bold">4. Security</h3>
            <p>We take reasonable measures to help protect information about you from loss, theft, misuse, and unauthorized access.</p>

            <h3 className="text-white font-bold">5. Contact Us</h3>
            <p>If you have any questions about this Privacy Policy, please contact us at privacy@poorn.ai.</p>
          </div>
        )}
      </div>
    </div>
  );
};

export default LegalDocs;